### PR TITLE
Update pipeline and notebooks for Elyra 1.0

### PR DESCRIPTION
**Pull request by kevin-bates**
Recent changes to Elyra (https://github.com/elyra-ai/elyra/pull/702) have improved the ability to clearly specify dependencies, eliminating the need to include subdirectories in order to have specified files included.  Due to this improvement, the notebooks also must ensure their outputs directory exists, as they were accidentally relying on the faulty dependency behaviors to create that directory.

This pull request changes the following:
- All notebooks depend on `util.py` and ensure near their startup that the outputs directory exists, creating if necessary.
- util.py has been added as a dependency where it wasn't before (although clean-us-data imported util.py, it didn't previously list it as a dependency but the dependency was satisfied by virtue of include-subdirectories being selected and the previous behavior that includes everything, even when no dependencies are listed).
- All nodes using include-subdirectories no longer use that option and appropriate dependencies (e.g., inputs/ACS* in elt-us-census) are now in place.
- Both eu-data and us-data pipelines (in addition to the dependency updates) have been reformatted for readability and change management.

With both these and the Elyra changes in place, pipeline submission has shown an approximate 70% improvement.

### CODE REVIEW

**Review by frreiss — APPROVED** [review]
LGTM

**Comment by frreiss** [comment]
@lresende Can you clarify what still needs to be done here? These code changes look pretty innocuous to me.

**Comment by lresende** [comment]
These changes require a change on Elyra that is in Master, but hasn’t been released yet. We should be able to make a release by end of the week.

**Comment by frreiss** [comment]
New Elyra release is out. Merging this PR.

**Comment by frreiss** [comment]
Never mind, @lresende already merged it

**Pull request merged**
